version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.kafka:spring-kafka-test
    versions:
    - 2.6.5
    - 2.6.7
  - dependency-name: org.apache.avro:avro
    versions:
    - 1.10.1
  - dependency-name: org.apache.kafka:kafka-clients
    versions:
    - 6.1.0-ce
  - dependency-name: io.confluent:kafka-avro-serializer
    versions:
    - 6.0.1
    - 6.1.0
  - dependency-name: io.confluent.ksql:ksqldb-rest-model
    versions:
    - 6.0.1
    - 6.1.0
  - dependency-name: io.confluent.ksql:ksqldb-rest-client
    versions:
    - 6.0.1
    - 6.1.0
  - dependency-name: org.testcontainers:kafka
    versions:
    - 1.15.1
  - dependency-name: junit:junit
    versions:
    - 4.13.1
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
